import {
  OperationalSite,
  SiteStockTransfer,
  Equipment,
  MaintenancePlan,
  MaintenanceWorkOrder,
  PurchaseRequest,
  PurchaseOrder,
  GoodsReceipt,
  TechnicalReport,
  AppNotification,
  Mission,
  PayrollPeriod,
  Payslip,
  AccountingAccount,
  JournalEntry,
  BankTransaction,
  OcrResultRecord,
} from '../types/advancedModules';

// ==========================================
// 1. SITES OPÉRATIONNELS (CORESI GABON / CONGO)
// ==========================================
export const INITIAL_SITES: OperationalSite[] = [
  {
    id: 'site-001',
    code: 'SITE-PNR-HQ',
    name: 'Base Opérationnelle & Ateliers de Pointe-Noire (Siège)',
    type: 'headquarters',
    address: 'Zone Industrielle de Mpita, BP 1420',
    city: 'Pointe-Noire',
    region: 'Kouilou',
    country: 'Congo',
    managerId: 'emp-001',
    managerName: 'Dr. Joseph Ndoundo',
    status: 'actif',
    projectsCount: 3,
    employeesCount: 28,
    materialsCount: 42,
    coordinates: { lat: -4.7833, lng: 11.8667 },
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'site-002',
    code: 'SITE-DJE-ONSHORE',
    name: 'Base Chantier Tuyauterie HP Djeno Onshore',
    type: 'construction_site',
    address: 'Terminal Pétrolier TotalEnergies Djeno',
    city: 'Djeno',
    region: 'Kouilou',
    country: 'Congo',
    managerId: 'emp-002',
    managerName: 'Ing. Paul Kimbembe',
    status: 'actif',
    projectsCount: 2,
    employeesCount: 14,
    materialsCount: 18,
    coordinates: { lat: -4.9167, lng: 11.95 },
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'site-003',
    code: 'SITE-NKO-OFFSHORE',
    name: 'Barge & Plateforme Pétrolière Nkossa Offshore',
    type: 'temporary_site',
    address: 'Champ Nkossa 60 km au large',
    city: 'Haute Mer Offshore',
    region: 'Golfe de Guinée',
    country: 'Congo',
    managerId: 'emp-002',
    managerName: 'Ing. Paul Kimbembe',
    status: 'actif',
    projectsCount: 1,
    employeesCount: 8,
    materialsCount: 9,
    coordinates: { lat: -5.2833, lng: 11.5833 },
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'site-004',
    code: 'SITE-POG-GABON',
    name: 'Antenne Logistique & Tuyauterie Port-Gentil',
    type: 'branch',
    address: 'Zone Portuaire du Cap Lopez',
    city: 'Port-Gentil',
    region: 'Ogooué-Maritime',
    country: 'Gabon',
    managerId: 'emp-004',
    managerName: 'Alexandre Makosso',
    status: 'actif',
    projectsCount: 1,
    employeesCount: 6,
    materialsCount: 12,
    coordinates: { lat: -0.7167, lng: 8.7833 },
    createdAt: '2026-03-15T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
];

export const INITIAL_SITE_TRANSFERS: SiteStockTransfer[] = [
  {
    id: 'trf-001',
    reference: 'TRF-2026-0001',
    sourceSiteId: 'site-001',
    sourceSiteName: 'Base Ateliers Pointe-Noire',
    targetSiteId: 'site-002',
    targetSiteName: 'Chantier Djeno Onshore',
    materialId: 'mat-001',
    materialName: 'Poste à Souder TIG/ARC 400A SAF-FRO',
    materialCode: 'MAT-SOU-01',
    quantity: 2,
    unit: 'unités',
    requestedBy: 'Ing. Paul Kimbembe',
    approvedBy: 'Alexandre Makosso',
    status: 'receptionne',
    requestDate: '2026-09-18T09:00:00Z',
    departureDate: '2026-09-18T14:00:00Z',
    receptionDate: '2026-09-19T08:30:00Z',
    receivedBy: 'Moussa Traoré',
    notes: 'Matériel requis pour soudage des brides 10" Sch 80.',
  },
  {
    id: 'trf-002',
    reference: 'TRF-2026-0002',
    sourceSiteId: 'site-001',
    sourceSiteName: 'Base Ateliers Pointe-Noire',
    targetSiteId: 'site-003',
    targetSiteName: 'Plateforme Nkossa Offshore',
    materialId: 'mat-003',
    materialName: 'Pompe d\'épreuve hydraulique 1000 Bars',
    materialCode: 'MAT-EPR-03',
    quantity: 1,
    unit: 'unité',
    requestedBy: 'Ing. Paul Kimbembe',
    approvedBy: 'Dr. Joseph Ndoundo',
    status: 'en_transit',
    requestDate: '2026-09-24T10:00:00Z',
    departureDate: '2026-09-25T06:00:00Z',
    notes: 'Expédition par navire de ravitaillement Bourbon.',
  },
];

// ==========================================
// 2. PARC GMAO & ÉQUIPEMENTS LOURDS
// ==========================================
export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-001',
    reference: 'EQ-2026-001',
    name: 'Poste de Soudage TIG/MIG SAF-FRO Presto 250',
    category: 'soudage',
    serialNumber: 'SN-SAF-2024-8839',
    manufacturer: 'SAF-FRO Air Liquide Welding',
    model: 'Presto 250 Force',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    location: 'Atelier Mobile Soudage Ligne 1',
    status: 'operationnel',
    commissioningDate: '2024-04-12',
    warrantyEndDate: '2026-04-12',
    operatingHours: 1420,
    totalMaintenanceCost: 280000,
    interventionsCount: 3,
    lastMaintenanceDate: '2026-08-15',
    nextScheduledMaintenance: '2026-11-15',
    createdAt: '2024-04-12T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'eq-002',
    reference: 'EQ-2026-002',
    name: 'Compresseur d\'Air Chantier Atlas Copco XAS 97',
    category: 'compresseur',
    serialNumber: 'SN-AC-99402-BE',
    manufacturer: 'Atlas Copco',
    model: 'XAS 97 Dd (5.3 m³/min)',
    siteId: 'site-001',
    siteName: 'Base Ateliers Pointe-Noire',
    projectId: 'prj-002',
    projectName: 'Maintenance Bac Stockage Pétrole (Perenco)',
    location: 'Aire d\'Essais Hydrauliques',
    status: 'en_maintenance',
    commissioningDate: '2023-06-20',
    warrantyEndDate: '2025-06-20',
    operatingHours: 3840,
    totalMaintenanceCost: 750000,
    interventionsCount: 5,
    lastMaintenanceDate: '2026-07-10',
    nextScheduledMaintenance: '2026-09-28',
    createdAt: '2023-06-20T08:00:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
  },
  {
    id: 'eq-003',
    reference: 'EQ-2026-003',
    name: 'Grue Mobile Tout-Terrain Grove RT540E (40 Tonnes)',
    category: 'levage',
    serialNumber: 'SN-GROVE-540-0982',
    manufacturer: 'Manitowoc / Grove',
    model: 'RT540E 40T',
    siteId: 'site-001',
    siteName: 'Base Ateliers Pointe-Noire',
    location: 'Parc Engins Lourdes',
    status: 'operationnel',
    commissioningDate: '2022-11-05',
    warrantyEndDate: '2024-11-05',
    operatingHours: 4210,
    totalMaintenanceCost: 2450000,
    interventionsCount: 8,
    lastMaintenanceDate: '2026-08-30',
    nextScheduledMaintenance: '2026-10-30',
    createdAt: '2022-11-05T08:00:00Z',
    updatedAt: '2026-09-22T11:00:00Z',
  },
  {
    id: 'eq-004',
    reference: 'EQ-2026-004',
    name: 'Groupe Électrogène Insonorisé Cummins 250 kVA',
    category: 'generateur',
    serialNumber: 'SN-CUM-2025-4411',
    manufacturer: 'Cummins Power Generation',
    model: 'C250 D5e',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    location: 'Sous-station Temporaire Djeno',
    status: 'operationnel',
    commissioningDate: '2025-01-18',
    warrantyEndDate: '2027-01-18',
    operatingHours: 2150,
    totalMaintenanceCost: 420000,
    interventionsCount: 4,
    lastMaintenanceDate: '2026-09-02',
    nextScheduledMaintenance: '2026-12-02',
    createdAt: '2025-01-18T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
];

export const INITIAL_MAINTENANCE_PLANS: MaintenancePlan[] = [
  {
    id: 'plan-001',
    equipmentId: 'eq-001',
    title: 'Révision Périodique & Calibration Torches TIG (Trimestrielle)',
    frequencyDays: 90,
    operations: [
      'Contrôle de l\'isolement haute fréquence',
      'Remplacement buses céramiques et diffuseurs',
      'Nettoyage interne soufflage dépoussiérage',
      'Contrôle débit électrovanne gaz argon',
      'Test de soudage témoin sur éprouvette inox',
    ],
    checklist: [
      'Câble de masse intact',
      'Manomètre gaz étalonné',
      'Ventilateur de refroidissement opérationnel',
      'Arrêt d\'urgence testé',
    ],
    estimatedDurationHours: 3.5,
    assignedRole: 'Technicien de Maintenance',
    active: true,
  },
  {
    id: 'plan-002',
    equipmentId: 'eq-002',
    title: 'Entretien Moteur Diesel & Séparateur d\'Air Compresseur (500h)',
    frequencyDays: 60,
    operations: [
      'Vidange huile moteur 15W40 et filtre huile',
      'Remplacement cartouche filtre à air primaire/secondaire',
      'Contrôle tension courroie alternateur',
      'Purge décanteur eau circuit gasoil',
      'Vérification tarage soupape de sécurité 8.5 bars',
    ],
    checklist: [
      'Niveau huile compresseur conforme',
      'Pression de service stable',
      'Aucune fuite gasoil ou huile',
      'Échappement sans fumée anormale',
    ],
    estimatedDurationHours: 5,
    assignedRole: 'Mécanicien Engins',
    active: true,
  },
];

export const INITIAL_WORK_ORDERS: MaintenanceWorkOrder[] = [
  {
    id: 'ot-001',
    reference: 'OT-2026-0042',
    equipmentId: 'eq-002',
    equipmentName: 'Compresseur d\'Air Atlas Copco XAS 97',
    type: 'corrective',
    priority: 'urgente',
    failureDescription: 'Baisse de pression anormale à 4.2 bars au sablage tuyauterie et voyant filtre colmaté allumé.',
    diagnostic: 'Cartouche de filtre séparateur d\'huile saturée et fuite sur durite de refoulement souple.',
    assignedTechnicianId: 'emp-005',
    assignedTechnicianName: 'Sébastien Nzamba (Mécanicien GMAO)',
    siteId: 'site-001',
    projectId: 'prj-002',
    partsUsed: [
      { description: 'Cartouche séparateur d\'huile Atlas Copco', quantity: 1, unitCost: 145000, totalCost: 145000 },
      { description: 'Durite hydraulique haute température 1"', quantity: 2, unitCost: 35000, totalCost: 70000 },
      { description: 'Colliers inox renforcés', quantity: 4, unitCost: 4500, totalCost: 18000 },
    ],
    laborHours: 4.5,
    laborRatePerHour: 15000,
    totalCost: 300500,
    status: 'en_cours',
    openedAt: '2026-09-24T08:30:00Z',
    reportNotes: 'Pièces sorties du magasin central. Montage en cours pour remise en service avant sablage bac.',
  },
  {
    id: 'ot-002',
    reference: 'OT-2026-0039',
    equipmentId: 'eq-001',
    equipmentName: 'Poste de Soudage TIG/MIG SAF-FRO',
    type: 'preventive',
    priority: 'normale',
    failureDescription: 'Maintenance préventive trimestrielle planifiée selon plan de charge chantier.',
    diagnostic: 'R.A.S. Remplacement pièces d\'usure courantes et étalonnage HF effectué avec succès.',
    assignedTechnicianId: 'emp-005',
    assignedTechnicianName: 'Sébastien Nzamba (Mécanicien GMAO)',
    siteId: 'site-002',
    projectId: 'prj-001',
    partsUsed: [
      { description: 'Kit diffuseurs & buses céramiques TIG', quantity: 2, unitCost: 18000, totalCost: 36000 },
      { description: 'Électrodes tungstène 2.4mm boîte de 10', quantity: 1, unitCost: 24000, totalCost: 24000 },
    ],
    laborHours: 2,
    laborRatePerHour: 15000,
    totalCost: 90000,
    status: 'cloture',
    openedAt: '2026-08-15T09:00:00Z',
    closedAt: '2026-08-15T12:00:00Z',
    reportNotes: 'Poste conforme pour qualification soudeur 6G ASME IX.',
  },
];

// ==========================================
// 3. ACHATS & CYCLE COMMANDES
// ==========================================
export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'da-001',
    reference: 'DA-2026-0128',
    requesterId: 'emp-002',
    requesterName: 'Ing. Paul Kimbembe (Chef de Projet)',
    departmentId: 'operations',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    items: [
      {
        id: 'item-1',
        description: 'Tubes acier carbone ASTM A106 Gr B 6" Sch 40 sans soudure',
        category: 'tuyauterie',
        quantity: 120,
        unit: 'mètres',
        estimatedUnitPrice: 48000,
        estimatedTotalPrice: 5760000,
      },
      {
        id: 'item-2',
        description: 'Brides à collerette WNRF Class 300 6" ASTM A105',
        category: 'tuyauterie',
        quantity: 16,
        unit: 'pièces',
        estimatedUnitPrice: 65000,
        estimatedTotalPrice: 1040000,
      },
      {
        id: 'item-3',
        description: 'Joints spiralés 6" 300# graphite inox 316',
        category: 'consommables',
        quantity: 20,
        unit: 'pièces',
        estimatedUnitPrice: 14500,
        estimatedTotalPrice: 290000,
      },
    ],
    reason: 'Raccordement de la nouvelle dérivation gaz vers torchère Djeno.',
    estimatedAmount: 7090000,
    currency: 'FCFA',
    priority: 'haute',
    status: 'approved',
    approvedBy: 'Dr. Joseph Ndoundo (DG)',
    approvedAt: '2026-09-20T14:30:00Z',
    createdAt: '2026-09-19T09:00:00Z',
    updatedAt: '2026-09-20T14:30:00Z',
  },
  {
    id: 'da-002',
    reference: 'DA-2026-0131',
    requesterId: 'emp-004',
    requesterName: 'Alexandre Makosso (Magasinier)',
    departmentId: 'logistique',
    siteId: 'site-001',
    siteName: 'Base Ateliers Pointe-Noire',
    items: [
      {
        id: 'item-4',
        description: 'Électrodes basiques E7018 diamètre 3.2mm (boîtes 5kg)',
        category: 'consommables',
        quantity: 40,
        unit: 'boîtes',
        estimatedUnitPrice: 18500,
        estimatedTotalPrice: 740000,
      },
      {
        id: 'item-5',
        description: 'Bouteilles gaz Argon pur soudage TIG B50 (recharges)',
        category: 'gaz_industriel',
        quantity: 15,
        unit: 'recharges',
        estimatedUnitPrice: 52000,
        estimatedTotalPrice: 780000,
      },
    ],
    reason: 'Réapprovisionnement stock de sécurité atelier avant contrôle QA Total.',
    estimatedAmount: 1520000,
    currency: 'FCFA',
    priority: 'normale',
    status: 'ordered',
    approvedBy: 'Dr. Joseph Ndoundo (DG)',
    approvedAt: '2026-09-22T10:00:00Z',
    createdAt: '2026-09-21T11:00:00Z',
    updatedAt: '2026-09-23T08:00:00Z',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'bc-001',
    reference: 'BC-2026-0089',
    requestId: 'da-001',
    supplierId: 'sup-001',
    supplierName: 'VALLOUREC TUBES AFRIQUE',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    items: [
      {
        id: 'item-1',
        description: 'Tubes acier carbone ASTM A106 Gr B 6" Sch 40 sans soudure',
        category: 'tuyauterie',
        quantity: 120,
        unit: 'mètres',
        estimatedUnitPrice: 46500,
        estimatedTotalPrice: 5580000,
      },
      {
        id: 'item-2',
        description: 'Brides à collerette WNRF Class 300 6" ASTM A105',
        category: 'tuyauterie',
        quantity: 16,
        unit: 'pièces',
        estimatedUnitPrice: 62000,
        estimatedTotalPrice: 992000,
      },
    ],
    subtotalAmount: 6572000,
    taxAmount: 1265110,
    totalAmount: 7837110,
    currency: 'FCFA',
    paymentTerms: 'Virement bancaire sous 30 jours fin de mois avec certificat matière 3.1',
    expectedDeliveryDate: '2026-10-05',
    status: 'envoye_fournisseur',
    approvedBy: 'Dr. Joseph Ndoundo (DG)',
    approvedAt: '2026-09-21T16:00:00Z',
    createdAt: '2026-09-21T15:00:00Z',
    updatedAt: '2026-09-22T08:30:00Z',
  },
];

export const INITIAL_GOODS_RECEIPTS: GoodsReceipt[] = [
  {
    id: 'rec-001',
    reference: 'REC-2026-0056',
    orderId: 'bc-001',
    orderReference: 'BC-2026-0089',
    supplierId: 'sup-001',
    supplierName: 'VALLOUREC TUBES AFRIQUE',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    receptionDate: '2026-09-24T14:00:00Z',
    receivedBy: 'Alexandre Makosso (Magasinier)',
    items: [
      {
        description: 'Tubes acier carbone ASTM A106 Gr B 6" Sch 40',
        orderedQuantity: 120,
        receivedQuantity: 120,
        damagedQuantity: 0,
        missingQuantity: 0,
        isStockable: true,
      },
      {
        description: 'Brides à collerette WNRF Class 300 6"',
        orderedQuantity: 16,
        receivedQuantity: 16,
        damagedQuantity: 0,
        missingQuantity: 0,
        isStockable: true,
      },
    ],
    deliveryNoteNumber: 'BL-VAL-2026-4401',
    observations: 'Colisage parfait, certificats matière EN 10204 3.1 conformes et contrôlés au PMI.',
    isComplete: true,
    status: 'conforme',
    stockUpdated: true,
    createdAt: '2026-09-24T14:30:00Z',
  },
];

// ==========================================
// 4. RAPPORTS TECHNIQUES & PROCÈS-VERBAUX (PV)
// ==========================================
export const INITIAL_TECHNICAL_REPORTS: TechnicalReport[] = [
  {
    id: 'rpt-001',
    reference: 'PV-2026-0034',
    type: 'epreuve_hydraulique',
    title: 'Procès-Verbal d\'Épreuve Hydraulique Sous Pression (Tronçon Gaz Ligne 4")',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    authorId: 'emp-002',
    authorName: 'Ing. Paul Kimbembe (Responsable QA/QC)',
    date: '2026-09-23',
    participants: [
      'Ing. Paul Kimbembe (Chef de Projet CORESI)',
      'Jean-Pierre Mbou (Contrôleur Soudage QA CORESI)',
      'Hervé Dubois (Inspecteur Tiers Bureau Veritas)',
      'Thierry Leroy (Représentant Client TotalEnergies EP)',
    ],
    summary: 'Mise en pression d\'épreuve hydraulique du manifold d\'injection gaz 4" Sch 80 selon spécification ASME B31.3.',
    observations: 'Pression de calcul : 42.5 bars. Pression d\'épreuve appliquée : 64.0 bars maintenue pendant 4 heures sans chute de pression ni suintement.',
    workPerformed: 'Remplissage eau douce filtrée inhibée, mise en pression par pompe d\'épreuve étalonnée, enregistrement manotherme graphique.',
    issues: 'Aucune anomalie détectée sur les 24 soudures circonférentielles.',
    recommendations: 'Vidange, soufflage à l\'air sec et inertage à l\'azote recommandé avant mise en service définitive.',
    reserves: 'Aucune réserve. Réception sans réserve prononcée.',
    actionItems: [
      {
        id: 'act-1',
        description: 'Séchage complet du circuit par passage de racleurs mousse',
        responsiblePerson: 'Jean-Pierre Mbou',
        deadlineDate: '2026-09-28',
        status: 'en_cours',
      },
    ],
    attachments: [
      {
        id: 'att-1',
        title: 'Manotherme d\'enregistrement 64 bars',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
        type: 'photo',
      },
      {
        id: 'att-2',
        title: 'Plan Isométrique Spool Gaz Rev C',
        url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=80',
        type: 'plan',
      },
    ],
    status: 'valide',
    validatedBy: 'Dr. Joseph Ndoundo (DG)',
    validatedAt: '2026-09-24T11:00:00Z',
    createdAt: '2026-09-23T16:00:00Z',
    updatedAt: '2026-09-24T11:00:00Z',
  },
  {
    id: 'rpt-002',
    reference: 'RPT-2026-0012',
    type: 'rapport_chantier',
    title: 'Rapport Hebdomadaire d\'Avancement des Travaux de Tuyauterie',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    siteId: 'site-002',
    siteName: 'Chantier Djeno Onshore',
    authorId: 'emp-002',
    authorName: 'Ing. Paul Kimbembe (Chef de Projet)',
    date: '2026-09-22',
    participants: ['Équipe Tuyauterie CORESI (12 ouvriers)', 'HSE TotalEnergies'],
    summary: 'Rapport d\'étape semaine 38 : achèvement du lignage des spools et soudage des collecteurs 6".',
    observations: 'Avancement physique global à 72%. Respect des cadences de production et 0 accident avec arrêt.',
    workPerformed: 'Préfabrication atelier de 18 spools, montage sur site de 65 mètres de ligne et 100% contrôles ressuage effectués.',
    issues: 'Attente livraison des joints métalloplastiques prévue début semaine prochaine.',
    recommendations: 'Maintenir l\'équipe renforcée le samedi matin pour préparer l\'épreuve hydraulique du tronçon secondaire.',
    attachments: [
      {
        id: 'att-3',
        title: 'Vue d\'ensemble chantier tuyauterie',
        url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80',
        type: 'photo',
      },
    ],
    status: 'valide',
    validatedBy: 'Dr. Joseph Ndoundo (DG)',
    validatedAt: '2026-09-23T09:00:00Z',
    createdAt: '2026-09-22T17:00:00Z',
    updatedAt: '2026-09-23T09:00:00Z',
  },
];

// ==========================================
// 5. MISSIONS PROFESSIONNELLES
// ==========================================
export const INITIAL_MISSIONS: Mission[] = [
  {
    id: 'mis-001',
    reference: 'MIS-2026-0024',
    employeeId: 'emp-002',
    employeeName: 'Ing. Paul Kimbembe',
    employeeMatricule: 'MAT-002',
    employeeRole: 'Chef de Projet & Ingénieur Soudage',
    projectId: 'prj-001',
    projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
    siteId: 'site-003',
    siteName: 'Barge & Plateforme Nkossa Offshore',
    destination: 'Champs Pétrolier Nkossa Offshore (Golfe de Guinée)',
    purpose: 'Supervision technique du raccordement des conduites flexibles sous-marines et validation des épreuves hydrauliques.',
    startDate: '2026-09-28',
    endDate: '2026-10-04',
    durationDays: 7,
    transportType: 'navire_offshore',
    accommodation: 'base_vie',
    estimatedCost: 1450000,
    advanceRequested: 600000,
    advanceGiven: 600000,
    advancePaymentMethod: 'Virement Bancaire (Compte Ecobank)',
    actualTotalCost: 0,
    balanceAmount: 600000,
    expenses: [],
    status: 'approuvee_dg',
    approvedBy: 'Dr. Joseph Ndoundo (DG)',
    approvedAt: '2026-09-24T16:00:00Z',
    createdAt: '2026-09-23T10:00:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
  },
  {
    id: 'mis-002',
    reference: 'MIS-2026-0021',
    employeeId: 'emp-003',
    employeeName: 'Jean-Pierre Mbou',
    employeeMatricule: 'MAT-003',
    employeeRole: 'Contrôleur CND & Soudage Certifié',
    projectId: 'prj-002',
    projectName: 'Maintenance Bac Stockage Pétrole (Perenco)',
    siteId: 'site-004',
    siteName: 'Antenne Logistique Port-Gentil',
    destination: 'Base Industrielle Perenco Port-Gentil (Gabon)',
    purpose: 'Contrôle non destructif (CND) par ultrasons TOFD et magnétoscopie sur les viroles du bac de stockage n°4.',
    startDate: '2026-09-10',
    endDate: '2026-09-16',
    durationDays: 7,
    transportType: 'avion',
    accommodation: 'hotel',
    estimatedCost: 1850000,
    advanceRequested: 900000,
    advanceGiven: 900000,
    actualTotalCost: 865000,
    balanceAmount: 35000, // 35 000 FCFA remboursé en caisse
    expenses: [
      { id: 'exp-m1', category: 'transport', date: '2026-09-10', amount: 420000, currency: 'FCFA', description: 'Billet d\'avion A/R Pointe-Noire - Port-Gentil (Equaflight)' },
      { id: 'exp-m2', category: 'hebergement', date: '2026-09-16', amount: 285000, currency: 'FCFA', description: 'Hôtel Le Méridien Mandji Port-Gentil (6 nuitées)' },
      { id: 'exp-m3', category: 'repas', date: '2026-09-16', amount: 160000, currency: 'FCFA', description: 'Forfait restauration et per diem légal de mission' },
    ],
    status: 'soldee',
    approvedBy: 'Dr. Joseph Ndoundo (DG)',
    approvedAt: '2026-09-08T15:00:00Z',
    liquidationNotes: 'Justificatifs contrôlés par la comptabilité. Reliquat de 35 000 FCFA reversé en caisse centrale le 18/09.',
    createdAt: '2026-09-07T09:00:00Z',
    updatedAt: '2026-09-18T14:00:00Z',
  },
];

// ==========================================
// 6. PAIE & BULLETINS DE SALAIRE
// ==========================================
export const INITIAL_PAYROLL_PERIODS: PayrollPeriod[] = [
  {
    id: 'pay-2026-08',
    periodKey: '2026-08',
    month: 8,
    year: 2026,
    status: 'cloture',
    totalGross: 14850000,
    totalNet: 12210000,
    totalDeductions: 2640000,
    totalEmployerContributions: 2376000,
    employeesCount: 16,
    calculatedAt: '2026-08-27T10:00:00Z',
    validatedBy: 'Dr. Joseph Ndoundo (DG)',
    validatedAt: '2026-08-28T14:00:00Z',
    closedAt: '2026-08-31T18:00:00Z',
    closedBy: 'Clarisse Bantsimba (Comptable)',
  },
  {
    id: 'pay-2026-09',
    periodKey: '2026-09',
    month: 9,
    year: 2026,
    status: 'controle',
    totalGross: 15420000,
    totalNet: 12690000,
    totalDeductions: 2730000,
    totalEmployerContributions: 2467200,
    employeesCount: 16,
    calculatedAt: '2026-09-24T16:00:00Z',
    validatedBy: undefined,
  },
];

export const INITIAL_PAYSLIPS: Payslip[] = [
  {
    id: 'ps-001',
    reference: 'PAY-2026-09-001',
    periodId: 'pay-2026-09',
    periodKey: '2026-09',
    employeeId: 'emp-002',
    matricule: 'MAT-002',
    employeeName: 'Ing. Paul Kimbembe',
    department: 'operations',
    role: 'Chef de Projet Tuyauterie',
    contractType: 'cdi',
    baseSalary: 1250000,
    workedDays: 22,
    overtimeHours: 12,
    overtimeAmount: 115000,
    seniorityBonus: 62500,
    offshoreBonus: 250000,
    hazardBonus: 100000,
    transportAllowance: 80000,
    housingAllowance: 150000,
    grossSalary: 2007500,
    employeeCnss: 84315, // 4.2% plafonné
    incomeTax: 215000, // IRPP
    advanceDeduction: 0,
    otherDeductions: 0,
    totalDeductions: 299315,
    netSalary: 1708185,
    employerCnss: 321200, // 16%
    totalEmployerCost: 2328700,
    paymentMethod: 'virement',
    paymentStatus: 'en_attente',
    generatedAt: '2026-09-24T16:30:00Z',
  },
  {
    id: 'ps-002',
    reference: 'PAY-2026-09-002',
    periodId: 'pay-2026-09',
    periodKey: '2026-09',
    employeeId: 'emp-003',
    matricule: 'MAT-003',
    employeeName: 'Jean-Pierre Mbou',
    department: 'operations',
    role: 'Soudeur TIG / CND Qualifié',
    contractType: 'cdi',
    baseSalary: 850000,
    workedDays: 22,
    overtimeHours: 24,
    overtimeAmount: 155000,
    seniorityBonus: 42500,
    offshoreBonus: 180000,
    hazardBonus: 85000,
    transportAllowance: 50000,
    housingAllowance: 0,
    grossSalary: 1362500,
    employeeCnss: 57225,
    incomeTax: 128000,
    advanceDeduction: 150000, // Acompte remboursé
    otherDeductions: 0,
    totalDeductions: 335225,
    netSalary: 1027275,
    employerCnss: 218000,
    totalEmployerCost: 1580500,
    paymentMethod: 'virement',
    paymentStatus: 'en_attente',
    generatedAt: '2026-09-24T16:30:00Z',
  },
];

// ==========================================
// 7. COMPTABILITÉ AVANCÉE (SYSCOHADA)
// ==========================================
export const INITIAL_ACCOUNTING_ACCOUNTS: AccountingAccount[] = [
  { id: 'acc-401', code: '401000', name: 'Fournisseurs d\'exploitation', type: 'passif', active: true, balanceDebit: 0, balanceCredit: 24500000 },
  { id: 'acc-411', code: '411000', name: 'Clients donneurs d\'ordre', type: 'actif', active: true, balanceDebit: 58900000, balanceCredit: 0 },
  { id: 'acc-512', code: '512100', name: 'Banque Société Générale Congo', type: 'actif', active: true, balanceDebit: 114250000, balanceCredit: 0 },
  { id: 'acc-513', code: '512200', name: 'Banque Ecobank Congo', type: 'actif', active: true, balanceDebit: 42800000, balanceCredit: 0 },
  { id: 'acc-571', code: '571000', name: 'Caisse Principale Siège', type: 'actif', active: true, balanceDebit: 3450000, balanceCredit: 0 },
  { id: 'acc-601', code: '601100', name: 'Achats Tubes Acier & Raccords', type: 'charge', active: true, balanceDebit: 32400000, balanceCredit: 0 },
  { id: 'acc-602', code: '602100', name: 'Achats Consommables Soudage & Gaz', type: 'charge', active: true, balanceDebit: 8900000, balanceCredit: 0 },
  { id: 'acc-613', code: '613000', name: 'Locations Matériels & Engins', type: 'charge', active: true, balanceDebit: 6500000, balanceCredit: 0 },
  { id: 'acc-622', code: '622000', name: 'Rémunérations Intermédiaires & Contrôles CND', type: 'charge', active: true, balanceDebit: 4200000, balanceCredit: 0 },
  { id: 'acc-641', code: '641000', name: 'Rémunérations du Personnel', type: 'charge', active: true, balanceDebit: 45000000, balanceCredit: 0 },
  { id: 'acc-701', code: '701100', name: 'Ventes Travaux Chaudronnerie & Tuyauterie', type: 'produit', active: true, balanceDebit: 0, balanceCredit: 168000000 },
];

export const INITIAL_JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'jnl-001',
    reference: 'JNL-2026-0084',
    date: '2026-09-24',
    description: 'Facturation Travaux Raccordement Gaz Djeno (TotalEnergies) - Situation n°2',
    journalCode: 'ventes',
    lines: [
      {
        id: 'jl-1',
        accountCode: '411000',
        accountName: 'Clients donneurs d\'ordre (TOTAL)',
        debit: 21465000,
        credit: 0,
        description: 'Créance Facture FAC-2026-0045 TotalEnergies',
        projectId: 'prj-001',
        siteId: 'site-002',
      },
      {
        id: 'jl-2',
        accountCode: '701100',
        accountName: 'Ventes Travaux Tuyauterie Industrielle',
        debit: 0,
        credit: 18000000,
        description: 'Prestation soudage & épreuve HP',
        projectId: 'prj-001',
        siteId: 'site-002',
      },
      {
        id: 'jl-3',
        accountCode: '443100',
        accountName: 'TVA Facturée sur Prestations (19.25%)',
        debit: 0,
        credit: 3465000,
        description: 'TVA collectée situation n°2',
        projectId: 'prj-001',
        siteId: 'site-002',
      },
    ],
    totalDebit: 21465000,
    totalCredit: 21465000,
    isBalanced: true,
    sourceType: 'facture',
    sourceId: 'inv-001',
    status: 'validee',
    createdBy: 'Clarisse Bantsimba (Comptable)',
    validatedBy: 'Dr. Joseph Ndoundo (DG)',
    validatedAt: '2026-09-24T17:00:00Z',
    createdAt: '2026-09-24T16:00:00Z',
  },
  {
    id: 'jnl-002',
    reference: 'JNL-2026-0085',
    date: '2026-09-24',
    description: 'Acquisition Tubes et Brides ASTM A106 Gr B (Vallourec Afrique)',
    journalCode: 'achats',
    lines: [
      {
        id: 'jl-4',
        accountCode: '601100',
        accountName: 'Achats Tubes Acier & Raccords',
        debit: 6572000,
        credit: 0,
        description: 'Achat tuyauterie 6" Sch 40 BC-2026-0089',
        projectId: 'prj-001',
        siteId: 'site-002',
      },
      {
        id: 'jl-5',
        accountCode: '445200',
        accountName: 'TVA Récupérable sur Achats (19.25%)',
        debit: 1265110,
        credit: 0,
        description: 'TVA déductible sur fourniture Vallourec',
        projectId: 'prj-001',
        siteId: 'site-002',
      },
      {
        id: 'jl-6',
        accountCode: '401000',
        accountName: 'Fournisseurs d\'exploitation (VALLOUREC)',
        debit: 0,
        credit: 7837110,
        description: 'Dette fournisseur exigible 30 jours',
        projectId: 'prj-001',
        siteId: 'site-002',
      },
    ],
    totalDebit: 7837110,
    totalCredit: 7837110,
    isBalanced: true,
    sourceType: 'reception',
    sourceId: 'rec-001',
    status: 'validee',
    createdBy: 'Clarisse Bantsimba (Comptable)',
    validatedBy: 'Dr. Joseph Ndoundo (DG)',
    validatedAt: '2026-09-24T17:30:00Z',
    createdAt: '2026-09-24T16:30:00Z',
  },
];

export const INITIAL_BANK_TRANSACTIONS: BankTransaction[] = [
  {
    id: 'bt-001',
    date: '2026-09-22',
    bankAccount: 'SG Congo 2100492019',
    reference: 'VIR-CLI-TOT-9921',
    label: 'Règlement Acompte 40% Contrat Djeno TotalEnergies EP',
    debit: 25000000,
    credit: 0,
    reconciledWithEntryId: 'jnl-001',
    reconciled: true,
  },
  {
    id: 'bt-002',
    date: '2026-09-23',
    bankAccount: 'SG Congo 2100492019',
    reference: 'PRELEV-CNSS-0826',
    label: 'Prélèvement Cotisations Sociales CNSS Période Août 2026',
    debit: 0,
    credit: 2640000,
    reconciled: true,
  },
];

// ==========================================
// 8. CENTRE DE NOTIFICATIONS
// ==========================================
export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-001',
    type: 'purchases',
    title: 'Demande d\'Achat à Valider (7 090 000 FCFA)',
    message: 'DA-2026-0128 soumise par Ing. Paul Kimbembe pour les tubes 6" du chantier Djeno.',
    recipientRole: 'dg',
    priority: 'high',
    read: false,
    entityType: 'purchaseRequest',
    entityId: 'da-001',
    projectId: 'prj-001',
    deepLink: 'purchases',
    createdAt: '2026-09-25T07:15:00Z',
  },
  {
    id: 'notif-002',
    type: 'maintenance',
    title: 'Intervention Urgente GMAO en Cours',
    message: 'Compresseur Atlas Copco XAS 97 arrêté pour filtre saturé (OT-2026-0042).',
    recipientRole: 'chef_projet',
    priority: 'critical',
    read: false,
    entityType: 'maintenanceWorkOrder',
    entityId: 'ot-001',
    deepLink: 'maintenance',
    createdAt: '2026-09-24T18:40:00Z',
  },
  {
    id: 'notif-003',
    type: 'reports',
    title: 'Nouveau PV d\'Épreuve Hydraulique Validé',
    message: 'Épreuve sous pression 64 bars approuvée sans réserve pour le chantier Djeno (PV-2026-0034).',
    recipientRole: 'all',
    priority: 'medium',
    read: true,
    entityType: 'technicalReport',
    entityId: 'rpt-001',
    projectId: 'prj-001',
    deepLink: 'reports',
    createdAt: '2026-09-24T12:00:00Z',
  },
  {
    id: 'notif-004',
    type: 'payroll',
    title: 'Période de Paie Septembre 2026 Prête pour Contrôle',
    message: 'Les calculs des 16 collaborateurs sont finalisés. Montant net total : 12 690 000 FCFA.',
    recipientRole: 'comptable',
    priority: 'high',
    read: false,
    entityType: 'payrollPeriod',
    entityId: 'pay-2026-09',
    deepLink: 'payroll',
    createdAt: '2026-09-24T17:00:00Z',
  },
  {
    id: 'notif-005',
    type: 'sites',
    title: 'Transfert de Matériel en Transit vers Nkossa Offshore',
    message: 'Pompe d\'épreuve hydraulique 1000 bars expédiée (TRF-2026-0002).',
    recipientRole: 'magasinier',
    priority: 'medium',
    read: false,
    entityType: 'siteTransfer',
    entityId: 'trf-002',
    deepLink: 'sites',
    createdAt: '2026-09-25T06:30:00Z',
  },
];

// ==========================================
// 9. OCR RESULTS RECORDS
// ==========================================
export const INITIAL_OCR_RESULTS: OcrResultRecord[] = [
  {
    id: 'ocr-res-001',
    originalFileName: 'Facture_Vallourec_Acier_Djeno.pdf',
    fileUrl: 'https://res.cloudinary.com/z2lmk5bs/image/upload/v1720000000/CORESI/factures/fac_vallourec.pdf',
    rawText: `
      VALLOUREC TUBES AFRIQUE
      FACTURE N° : FAC-2026-8819
      DATE : 24/09/2026
      CLIENT : CORESI INTERNATIONAL SARL
      CHANTIER : Raccordement Gaz Djeno (TotalEnergies)
      LIGNE 1 : Tube Acier ASTM A106 Gr B 6" Sch 40 - 120m x 46 500 = 5 580 000 FCFA
      LIGNE 2 : Brides WNRF Class 300 6" - 16 pcs x 62 000 = 992 000 FCFA
      TOTAL HT : 6 572 000 FCFA
      TVA 19.25% : 1 265 110 FCFA
      TOTAL TTC : 7 837 110 FCFA
    `.trim(),
    proposedClassification: 'facture',
    finalClassification: 'facture',
    extractedData: {
      documentNumber: 'FAC-2026-8819',
      documentDate: '2026-09-24',
      supplierName: 'VALLOUREC TUBES AFRIQUE',
      clientName: 'CORESI INTERNATIONAL SARL',
      amountHT: 6572000,
      vatAmount: 1265110,
      amountTTC: 7837110,
      currency: 'FCFA',
      projectName: 'Raccordement Gaz Djeno (TotalEnergies)',
      lines: [
        { description: 'Tube Acier ASTM A106 Gr B 6" Sch 40', quantity: 120, unitPrice: 46500, totalPrice: 5580000 },
        { description: 'Brides WNRF Class 300 6"', quantity: 16, unitPrice: 62000, totalPrice: 992000 },
      ],
      confidenceScores: {
        documentNumber: 99,
        documentDate: 98,
        amounts: 97,
        parties: 96,
        overall: 97.5,
      },
    },
    confidenceScore: 97.5,
    engineUsed: 'gemini_vision',
    status: 'validated',
    processedAt: '2026-09-24T15:20:00Z',
    validatedAt: '2026-09-24T15:30:00Z',
    validatedBy: 'Clarisse Bantsimba (Comptable)',
  },
];
