import {
  Project,
  DocumentRecord,
  Expense,
  Invoice,
  Employee,
  Material,
  Client,
  Supplier,
  AuditLog,
} from '../types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    code: 'CLI-TOT-01',
    name: 'TOTAL CONGO EP',
    contactPerson: 'Marcelle Nguesso (Directeur Projets Offshore)',
    email: 'm.nguesso@totalcongo.cg',
    phone: '+242 06 612 34 56',
    address: 'Base Industrielle de Djeno, Pointe-Noire',
    sector: 'Pétrole & Gaz Offshore',
    activeProjectsCount: 2,
    createdAt: '2026-01-10T08:00:00Z',
  },
  {
    id: 'cli-002',
    code: 'CLI-PER-02',
    name: 'PERENCO RDC',
    contactPerson: 'Antoine Kalonji (Chef de Maintenance Usine)',
    email: 'a.kalonji@perenco.com',
    phone: '+243 81 555 78 90',
    address: 'Terminal Pétrolier de Muanda',
    sector: 'Exploitation Pétrolière',
    activeProjectsCount: 1,
    createdAt: '2026-02-01T09:30:00Z',
  },
  {
    id: 'cli-003',
    code: 'CLI-EIF-03',
    name: 'EIFFAGE ENERGIE SYSTEMES',
    contactPerson: 'Hervé Dubois (Directeur Grands Chantiers)',
    email: 'h.dubois@eiffage.com',
    phone: '+242 05 522 11 00',
    address: 'Zone Industrielle Ouest, Brazzaville',
    sector: 'Infrastructures & Énergie',
    activeProjectsCount: 1,
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'cli-004',
    code: 'CLI-DAN-04',
    name: 'DANGOTE CEMENT SARL',
    contactPerson: 'Ibrahim Al-Hassan (Responsable Maintenance)',
    email: 'i.alhassan@dangote.com',
    phone: '+242 04 433 99 22',
    address: 'Usine de Mfila, District de Yamba',
    sector: 'Cimenterie & Industrie Lourde',
    activeProjectsCount: 1,
    createdAt: '2026-03-01T14:00:00Z',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-001',
    code: 'FOUR-VAL-01',
    name: 'VALLOUREC TUBES AFRIQUE',
    category: 'Tubes acier sans soudure & Brides',
    contactPerson: 'Christian Moreau',
    email: 'c.moreau@vallourec.com',
    phone: '+33 1 49 01 00 00',
    address: 'Dépôt Régional Port Autonome de Pointe-Noire',
    createdAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'sup-002',
    code: 'FOUR-AIR-02',
    name: 'AIR LIQUIDE CONGO',
    category: 'Gaz industriels & Baguettes soudure',
    contactPerson: 'Blandine Massamba',
    email: 'commandes@airliquide.cg',
    phone: '+242 06 633 44 55',
    address: 'Boulevard Maritime, Zone Portuaire',
    createdAt: '2026-01-20T08:15:00Z',
  },
  {
    id: 'sup-003',
    code: 'FOUR-BUR-03',
    name: 'BUREAU VERITAS AFRIQUE',
    category: 'Inspection technique & Certification CND',
    contactPerson: 'Pauline Mbemba',
    email: 'p.mbemba@bureauveritas.com',
    phone: '+242 05 511 22 33',
    address: 'Avenue Charles de Gaulle, Pointe-Noire',
    createdAt: '2026-02-05T16:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj-001',
    code: 'PRJ-2026-01',
    name: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    clientId: 'cli-001',
    clientName: 'TOTAL CONGO EP',
    category: 'tuyauterie',
    location: 'Terminal Pétrolier Djeno (Pointe-Noire)',
    budget: 45000000,
    spent: 28400000,
    progress: 68,
    status: 'in_progress',
    startDate: '2026-01-15',
    endDate: '2026-06-30',
    managerId: 'emp-002',
    managerName: 'Ing. Paul Kimbembe (Ingénieur Tuyauterie & QA)',
    description: 'Remplacement de 450 mètres de tuyauterie 6 pouces haute pression Sch 80 avec épreuve hydraulique 65 bars et CND.',
    assignedWorkersCount: 14,
    documentsCount: 6,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-09-20T16:30:00Z',
  },
  {
    id: 'prj-002',
    code: 'PRJ-2026-02',
    name: 'Construction Charpente Métallique Silo 3 - Mfila',
    clientId: 'cli-004',
    clientName: 'DANGOTE CEMENT SARL',
    category: 'charpente',
    location: 'Usine de Cimenterie, Yamba',
    budget: 68000000,
    spent: 54100000,
    progress: 82,
    status: 'in_progress',
    startDate: '2026-02-01',
    endDate: '2026-05-30',
    managerId: 'emp-003',
    managerName: 'Alexandre Makosso (Chef d\'Atelier Chaudronnerie)',
    description: 'Fabrication en atelier et montage sur site d\'une ossature métallique de 120 tonnes avec passerelles de visite.',
    assignedWorkersCount: 18,
    documentsCount: 8,
    createdAt: '2026-01-25T11:00:00Z',
    updatedAt: '2026-09-22T14:20:00Z',
  },
  {
    id: 'prj-003',
    code: 'PRJ-2026-03',
    name: 'Maintenance Chaudronnerie & Séparateurs Triphasiques',
    clientId: 'cli-002',
    clientName: 'PERENCO RDC',
    category: 'chaudronnerie',
    location: 'Plateforme Offshore Muanda',
    budget: 32000000,
    spent: 12800000,
    progress: 40,
    status: 'in_progress',
    startDate: '2026-03-01',
    endDate: '2026-07-15',
    managerId: 'emp-002',
    managerName: 'Ing. Paul Kimbembe',
    description: 'Réchampissage, doublage de viroles et réfection des tubulures sur 2 séparateurs gaz/huile/eau.',
    assignedWorkersCount: 8,
    documentsCount: 4,
    createdAt: '2026-02-20T08:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
  },
  {
    id: 'prj-004',
    code: 'PRJ-2026-04',
    name: 'Génie Civil Fondations Turbines Électriques',
    clientId: 'cli-003',
    clientName: 'EIFFAGE ENERGIE SYSTEMES',
    category: 'genie_civil',
    location: 'Centrale Électrique Maloukou',
    budget: 52000000,
    spent: 51200000,
    progress: 100,
    status: 'completed',
    startDate: '2025-10-01',
    endDate: '2026-02-28',
    managerId: 'emp-001',
    managerName: 'Dr. Joseph Ndoundo (Directeur Technique)',
    description: 'Ouvrage en béton armé banché haute densité résistant aux vibrations dynamiques de turbines 25 MW.',
    assignedWorkersCount: 22,
    documentsCount: 12,
    createdAt: '2025-09-15T09:00:00Z',
    updatedAt: '2026-03-05T12:00:00Z',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    matricule: 'COR-DIR-001',
    fullName: 'Dr. Joseph Ndoundo',
    role: 'Directeur Général & Ingénieur Conseil',
    department: 'direction',
    phone: '+242 06 600 11 22',
    email: 'j.ndoundo@coresi-international.com',
    salary: 4500000,
    contractType: 'cdi',
    status: 'actif',
    hireDate: '2020-01-05',
    documentsCount: 3,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-002',
    matricule: 'COR-ING-004',
    fullName: 'Ing. Paul Kimbembe',
    role: 'Chef de Projets Tuyauterie & Contrôle Qualité',
    department: 'ingenierie',
    phone: '+242 05 512 88 99',
    email: 'p.kimbembe@coresi-international.com',
    salary: 2800000,
    contractType: 'cdi',
    assignedProjectId: 'prj-001',
    assignedProjectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    status: 'actif',
    hireDate: '2021-06-15',
    documentsCount: 4,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-003',
    matricule: 'COR-OPS-012',
    fullName: 'Alexandre Makosso',
    role: 'Chef d\'Atelier Chaudronnerie & Montage',
    department: 'chaudronnerie',
    phone: '+242 06 945 67 12',
    email: 'a.makosso@coresi-international.com',
    salary: 1950000,
    contractType: 'cdi',
    assignedProjectId: 'prj-002',
    assignedProjectName: 'Construction Charpente Métallique Silo 3 - Mfila',
    status: 'actif',
    hireDate: '2022-03-10',
    documentsCount: 2,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-004',
    matricule: 'COR-ADM-003',
    fullName: 'Clarisse Bantsimba',
    role: 'Responsable Administratif & Financier (RAF)',
    department: 'comptabilite',
    phone: '+242 05 678 90 12',
    email: 'c.bantsimba@coresi-international.com',
    salary: 2200000,
    contractType: 'cdi',
    status: 'actif',
    hireDate: '2021-01-10',
    documentsCount: 5,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'emp-005',
    matricule: 'COR-SOU-025',
    fullName: 'Moussa Traoré',
    role: 'Soudeur Haute Pression Qualifié 6G (ASME IX)',
    department: 'tuyauterie',
    phone: '+242 06 721 34 89',
    email: 'm.traore@coresi-international.com',
    salary: 1400000,
    contractType: 'cdi',
    assignedProjectId: 'prj-001',
    assignedProjectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    status: 'actif',
    hireDate: '2023-04-01',
    documentsCount: 3,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

export const INITIAL_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'doc-001',
    title: 'Facture Vallourec - Tubes Sans Soudure 6" Sch 80',
    documentNumber: 'FAC-2026-0045',
    category: 'factures',
    cloudinary: {
      publicId: 'CORESI/projects/prj-001/documents/fac_vallourec_tubes',
      secureUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
      resourceType: 'image',
      format: 'jpg',
      bytes: 842100,
      width: 1920,
      height: 1080,
      pageCount: 2,
      folder: 'CORESI/projects/prj-001/documents',
    },
    ocr: {
      text: `CORESI INTERNATIONAL SARL - GED ARCHIVES
FACTURE FOURNISSEUR N° FAC-2026-0045
Émetteur: VALLOUREC TUBES INDUSTRIE AFRIQUE
Destinataire: CORESI INTERNATIONAL SARL
Client final: TOTAL CONGO EP
Projet: Rénovation Lignes Tuyauterie HP - Terminal Djeno (PRJ-2026-01)
Date de facturation: 12/02/2026
Montant total: 14 500 000 FCFA TTC
Réf commande: BC-COR-2026-88
Spécification technique: Tubes acier carbone ASTM A106 Gr B, 6 pouces Sch 80, biseautés pour soudage. Certificat matière 3.1 EN 10204 fourni.`,
      confidence: 98.2,
      detectedFields: {
        documentNumber: 'FAC-2026-0045',
        documentDate: '12/02/2026',
        amount: 14500000,
        currency: 'FCFA',
        vendorOrClient: 'VALLOUREC TUBES AFRIQUE',
        category: 'factures',
        projectId: 'prj-001',
      },
      processedAt: '2026-02-12T14:30:00Z',
    },
    context: {
      projectId: 'prj-001',
      projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
      clientId: 'cli-001',
      clientName: 'TOTAL CONGO EP',
      supplierId: 'sup-001',
      supplierName: 'VALLOUREC TUBES AFRIQUE',
      expenseId: 'exp-001',
    },
    metadata: {
      documentDate: '2026-02-12',
      amount: 14500000,
      currency: 'FCFA',
      description: 'Facture acquittée d\'achat de tuyaux HP pour le chantier Total Djeno.',
      tags: ['tuyauterie', 'facture', 'vallourec', 'djeno', 'total_congo'],
    },
    status: 'validated',
    uploadedBy: 'Clarisse Bantsimba (RAF)',
    uploadedById: 'user-raf',
    createdAt: '2026-02-12T14:32:00Z',
    updatedAt: '2026-02-13T09:10:00Z',
  },
  {
    id: 'doc-002',
    title: 'Rapport CND & Épreuve Hydraulique 65 Bars - Bureau Veritas',
    documentNumber: 'PV-BV-2026-089',
    category: 'rapports',
    cloudinary: {
      publicId: 'CORESI/projects/prj-001/reports/pv_cnd_bureau_veritas',
      secureUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
      resourceType: 'image',
      format: 'jpg',
      bytes: 1250300,
      width: 1920,
      height: 1080,
      pageCount: 3,
      folder: 'CORESI/projects/prj-001/reports',
    },
    ocr: {
      text: `PROCÈS-VERBAL DE CONTRÔLE NON DESTRUCTIF (CND) & HYDROTEST
Organisme de contrôle tierce partie : BUREAU VERITAS AFRIQUE
Chantier : TOTAL CONGO EP - Terminal Djeno
Prestataire chaudronnerie & tuyauterie : CORESI INTERNATIONAL SARL
Réf PV: PV-BV-2026-089
Date d'inspection: 04/03/2026
Lignes inspectées: L-101 et L-102 (diamètre 6")
Résultats:
- Contrôle radiographique (RT): 100% soudures conformes ASME B31.3 Catégorie D
- Épreuve hydraulique sous pression stabilisée à 65 bars pendant 4 heures : AUCUNE FUITE DÉTECTÉE
Conclusion: Lignes approuvées pour mise en service industrielle.`,
      confidence: 97.8,
      detectedFields: {
        documentNumber: 'PV-BV-2026-089',
        documentDate: '04/03/2026',
        vendorOrClient: 'BUREAU VERITAS AFRIQUE',
        category: 'rapports',
        projectId: 'prj-001',
      },
      processedAt: '2026-03-04T17:00:00Z',
    },
    context: {
      projectId: 'prj-001',
      projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
      clientId: 'cli-001',
      clientName: 'TOTAL CONGO EP',
      supplierId: 'sup-003',
      supplierName: 'BUREAU VERITAS AFRIQUE',
    },
    metadata: {
      documentDate: '2026-03-04',
      description: 'PV de contrôle et certificat d\'épreuve hydraulique validé par Bureau Veritas.',
      tags: ['cnd', 'qualite', 'bureau_veritas', 'hydrotest', 'conformite'],
    },
    status: 'validated',
    uploadedBy: 'Ing. Paul Kimbembe',
    uploadedById: 'user-ing',
    createdAt: '2026-03-04T17:15:00Z',
    updatedAt: '2026-03-04T17:15:00Z',
  },
  {
    id: 'doc-003',
    title: 'Contrat Travaux Silo 3 - Dangote Cement',
    documentNumber: 'CTR-2026-DAN-03',
    category: 'contrats',
    cloudinary: {
      publicId: 'CORESI/projects/prj-002/documents/contrat_dangote_silo3',
      secureUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=1200&q=80',
      resourceType: 'image',
      format: 'jpg',
      bytes: 1890000,
      width: 1920,
      height: 1080,
      pageCount: 12,
      folder: 'CORESI/projects/prj-002/documents',
    },
    ocr: {
      text: `CONTRAT DE PRESTATION DE CONSTRUCTION INDUSTRIELLE & CHARPENTE
ENTRE :
La société DANGOTE CEMENT SARL (Le Maître d'Ouvrage)
ET :
La société CORESI INTERNATIONAL SARL (L'Entrepreneur)
Objet du marché: Construction et montage d'une ossature métallique pour Silo 3
Montant forfaitaire contractuel: 68 000 000 FCFA HT
Délai d'exécution: 120 jours calendaires
Pénalités de retard: 0.5% par jour de retard plafonné à 10%
Signé le 28/01/2026 à Brazzaville.`,
      confidence: 99.1,
      detectedFields: {
        documentNumber: 'CTR-2026-DAN-03',
        documentDate: '28/01/2026',
        amount: 68000000,
        currency: 'FCFA',
        vendorOrClient: 'DANGOTE CEMENT SARL',
        category: 'contrats',
        projectId: 'prj-002',
      },
      processedAt: '2026-01-29T10:00:00Z',
    },
    context: {
      projectId: 'prj-002',
      projectName: 'Construction Charpente Métallique Silo 3 - Mfila',
      clientId: 'cli-004',
      clientName: 'DANGOTE CEMENT SARL',
    },
    metadata: {
      documentDate: '2026-01-28',
      amount: 68000000,
      currency: 'FCFA',
      description: 'Contrat commercial principal signé avec la direction de Dangote Cement.',
      tags: ['contrat', 'juridique', 'dangote', 'charpente', 'marche'],
    },
    status: 'validated',
    uploadedBy: 'Dr. Joseph Ndoundo (DG)',
    uploadedById: 'user-dg',
    createdAt: '2026-01-29T10:20:00Z',
    updatedAt: '2026-01-29T10:20:00Z',
  },
  {
    id: 'doc-004',
    title: 'Bon de Livraison Gaz Argon & O2 - Air Liquide',
    documentNumber: 'BL-ALC-2026-312',
    category: 'bons_livraison',
    cloudinary: {
      publicId: 'CORESI/projects/prj-001/documents/bl_air_liquide',
      secureUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80',
      resourceType: 'image',
      format: 'jpg',
      bytes: 654000,
      width: 1920,
      height: 1080,
      pageCount: 1,
      folder: 'CORESI/projects/prj-001/documents',
    },
    ocr: {
      text: `AIR LIQUIDE CONGO SARL
BON DE LIVRAISON N° BL-ALC-2026-312
Date: 18/02/2026
Livreur: Agence Portuaire Pointe-Noire
Client: CORESI INTERNATIONAL SARL
Chantier: Total Djeno (PRJ-2026-01)
Articles livrés:
- 15 Bouteilles B50 Argon pur 99.99% pour soudage TIG
- 10 Bouteilles B50 Oxygène industriel
- 5 Paquets baguettes TIG ER70S-6 diamètre 2.4mm
Réceptionné par: Alexandre Makosso, sans réserve.`,
      confidence: 96.5,
      detectedFields: {
        documentNumber: 'BL-ALC-2026-312',
        documentDate: '18/02/2026',
        vendorOrClient: 'AIR LIQUIDE CONGO',
        category: 'bons_livraison',
        projectId: 'prj-001',
      },
      processedAt: '2026-02-18T16:00:00Z',
    },
    context: {
      projectId: 'prj-001',
      projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
      supplierId: 'sup-002',
      supplierName: 'AIR LIQUIDE CONGO',
    },
    metadata: {
      documentDate: '2026-02-18',
      description: 'BL de réapprovisionnement bouteilles gaz et consommables de soudage.',
      tags: ['bon_livraison', 'argon', 'soudure', 'air_liquide', 'chantier'],
    },
    status: 'validated',
    uploadedBy: 'Alexandre Makosso',
    uploadedById: 'user-ops',
    createdAt: '2026-02-18T16:15:00Z',
    updatedAt: '2026-02-18T16:15:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-001',
    reference: 'DEP-2026-0032',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    category: 'materiel',
    amount: 14500000,
    currency: 'FCFA',
    paymentMethod: 'virement_bancaire',
    supplierId: 'sup-001',
    supplierName: 'VALLOUREC TUBES AFRIQUE',
    date: '2026-02-12',
    description: 'Achat de 450m tubes acier sans soudure ASTM A106 Gr B 6" Sch 80.',
    documentId: 'doc-001',
    documentUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    status: 'paye',
    validationStatus: 'bon_a_payer_accorde',
    approvedBy: 'Dr. Joseph Ndoundo',
    approvedByDG: 'Dr. Joseph Ndoundo',
    approvedAt: '2026-02-12T14:45:00Z',
    createdAt: '2026-02-12T15:00:00Z',
    updatedAt: '2026-02-14T11:00:00Z',
  },
  {
    id: 'exp-002',
    reference: 'DEP-2026-0044',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    category: 'consommable',
    amount: 2850000,
    currency: 'FCFA',
    paymentMethod: 'cheque',
    supplierId: 'sup-002',
    supplierName: 'AIR LIQUIDE CONGO',
    date: '2026-02-19',
    description: 'Bouteilles gaz argon haute pureté et métal d\'apport pour qualification soudeurs.',
    documentId: 'doc-004',
    documentUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80',
    status: 'paye',
    validationStatus: 'bon_a_payer_accorde',
    approvedBy: 'Clarisse Bantsimba',
    approvedByDG: 'Dr. Joseph Ndoundo',
    approvedAt: '2026-02-19T11:00:00Z',
    createdAt: '2026-02-19T10:00:00Z',
    updatedAt: '2026-02-20T08:30:00Z',
  },
  {
    id: 'exp-003',
    reference: 'DEP-2026-0056',
    projectId: 'prj-002',
    projectName: 'Construction Charpente Métallique Silo 3 - Mfila',
    category: 'sous_traitance',
    amount: 4500000,
    currency: 'FCFA',
    paymentMethod: 'virement_bancaire',
    supplierId: 'sup-003',
    supplierName: 'BUREAU VERITAS AFRIQUE',
    date: '2026-03-05',
    description: 'Contrôles ultrasons des assemblages soudés et certification de résistance.',
    status: 'en_attente',
    validationStatus: 'en_attente_dg',
    approvedBy: 'En attente de visa DG',
    createdAt: '2026-03-05T14:00:00Z',
    updatedAt: '2026-03-06T09:00:00Z',
  },
  {
    id: 'exp-004',
    reference: 'DEP-2026-0061',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    category: 'frais_chantier',
    amount: 850000,
    currency: 'FCFA',
    paymentMethod: 'caisse',
    date: '2026-03-12',
    description: 'Avance carburant groupe électrogène chantier Djeno et équipement EPI.',
    status: 'paye',
    validationStatus: 'bon_a_payer_accorde',
    approvedBy: 'Clarisse Bantsimba',
    approvedByDG: 'Dr. Joseph Ndoundo',
    approvedAt: '2026-03-12T08:15:00Z',
    createdAt: '2026-03-12T08:00:00Z',
    updatedAt: '2026-03-12T08:00:00Z',
  },
  {
    id: 'exp-005',
    reference: 'DEP-2026-0072',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    category: 'materiel',
    amount: 3200000,
    currency: 'FCFA',
    paymentMethod: 'virement_bancaire',
    supplierName: 'PONTICELLI AFRIQUE',
    date: '2026-03-22',
    description: 'Location compresseur haute pression 12 bars pour nettoyage lignes de purge.',
    status: 'en_attente',
    validationStatus: 'en_attente_dg',
    approvedBy: 'En attente de visa DG',
    createdAt: '2026-03-22T09:30:00Z',
    updatedAt: '2026-03-22T09:30:00Z',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-001',
    invoiceNumber: 'FAC-COR-2026-01',
    type: 'client',
    partyName: 'TOTAL CONGO EP',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    issueDate: '2026-02-01',
    dueDate: '2026-03-05',
    totalAmount: 22500000,
    paidAmount: 22500000,
    currency: 'FCFA',
    status: 'paye',
    notes: 'Acompte 50% au démarrage du chantier et approvisionnement des tubes.',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-03-04T15:30:00Z',
  },
  {
    id: 'inv-002',
    invoiceNumber: 'FAC-COR-2026-02',
    type: 'client',
    partyName: 'DANGOTE CEMENT SARL',
    projectId: 'prj-002',
    projectName: 'Construction Charpente Métallique Silo 3 - Mfila',
    issueDate: '2026-02-15',
    dueDate: '2026-03-30',
    totalAmount: 34000000,
    paidAmount: 20000000,
    currency: 'FCFA',
    status: 'partiel',
    notes: 'Situation n°1 d\'avancement charpente atelier.',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-03-15T11:00:00Z',
  },
  {
    id: 'inv-003',
    invoiceNumber: 'FAC-VAL-2026-0045',
    type: 'fournisseur',
    partyName: 'VALLOUREC TUBES AFRIQUE',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    issueDate: '2026-02-12',
    dueDate: '2026-03-15',
    totalAmount: 14500000,
    paidAmount: 14500000,
    currency: 'FCFA',
    status: 'paye',
    documentId: 'doc-001',
    notes: 'Payé par virement bancaire Société Générale.',
    createdAt: '2026-02-12T14:30:00Z',
    updatedAt: '2026-02-14T10:00:00Z',
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 'mat-001',
    code: 'MAT-SOU-01',
    name: 'Poste de soudage TIG/MMA Miller Dynasty 400',
    category: 'soudage',
    quantity: 4,
    unit: 'unités',
    condition: 'bon_etat',
    location: 'Chantier Djeno',
    assignedProjectId: 'prj-001',
    assignedProjectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    status: 'assigne',
    lastMaintenanceDate: '2026-01-12',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'mat-002',
    code: 'MAT-LEV-02',
    name: 'Grue Mobile Tout-Terrain Tadano 50 Tonnes',
    category: 'levage',
    quantity: 1,
    unit: 'unité',
    condition: 'bon_etat',
    location: 'Chantier Dangote Mfila',
    assignedProjectId: 'prj-002',
    assignedProjectName: 'Construction Charpente Métallique Silo 3 - Mfila',
    status: 'assigne',
    lastMaintenanceDate: '2026-02-05',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-02-01T08:00:00Z',
  },
  {
    id: 'mat-003',
    code: 'MAT-ENG-03',
    name: 'Groupe Électrogène Insonorisé Cummins 150 kVA',
    category: 'outillage',
    quantity: 2,
    unit: 'unités',
    condition: 'bon_etat',
    location: 'Base Logistique Pointe-Noire',
    status: 'disponible',
    lastMaintenanceDate: '2026-03-01',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-03-01T14:00:00Z',
  },
  {
    id: 'mat-004',
    code: 'MAT-HYD-04',
    name: 'Pompe d\'Épreuve Hydraulique Haute Pression 250 Bars',
    category: 'outillage',
    quantity: 1,
    unit: 'unité',
    condition: 'neuf',
    location: 'Chantier Djeno',
    assignedProjectId: 'prj-001',
    assignedProjectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    status: 'assigne',
    lastMaintenanceDate: '2026-02-25',
    createdAt: '2026-01-05T09:00:00Z',
    updatedAt: '2026-02-28T16:00:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    action: 'document_scanned',
    entity: 'document',
    entityId: 'doc-001',
    userId: 'user-raf',
    userName: 'Clarisse Bantsimba (RAF)',
    userRole: 'comptable',
    timestamp: '2026-02-12T14:32:00Z',
    details: 'Numérisation Smart Scanner de la facture Vallourec FAC-2026-0045 avec reconnaissance OCR automatique et rattachement au projet PRJ-2026-01.',
  },
  {
    id: 'aud-002',
    action: 'expense_created',
    entity: 'expense',
    entityId: 'exp-001',
    userId: 'user-raf',
    userName: 'Clarisse Bantsimba (RAF)',
    userRole: 'comptable',
    timestamp: '2026-02-12T15:00:00Z',
    details: 'Création de la dépense DEP-2026-0032 (14 500 000 FCFA) générée directement depuis le scan de facture.',
  },
  {
    id: 'aud-003',
    action: 'document_validated',
    entity: 'document',
    entityId: 'doc-002',
    userId: 'user-ing',
    userName: 'Ing. Paul Kimbembe',
    userRole: 'chef_projet',
    timestamp: '2026-03-04T17:15:00Z',
    details: 'Validation du PV de contrôle Bureau Veritas PV-BV-2026-089 (épreuve 65 bars).',
  },
  {
    id: 'aud-004',
    action: 'project_updated',
    entity: 'project',
    entityId: 'prj-001',
    userId: 'user-dg',
    userName: 'Dr. Joseph Ndoundo',
    userRole: 'dg',
    timestamp: '2026-09-20T16:30:00Z',
    details: 'Mise à jour de l\'avancement physique du projet Djeno à 68%.',
  },
];

export const INITIAL_ADVANCES = [
  {
    id: 'adv-001',
    employeeId: 'emp-005',
    employeeName: 'Moussa Traoré',
    amount: 350000,
    currency: 'FCFA',
    requestDate: '2026-03-01',
    reason: 'Avance exceptionnelle déplacement urgent chantier Djeno',
    status: 'accordee' as const,
    repaymentMode: 'retenue_salaire' as const,
    justificationNotes: 'Retenue prévue sur le bulletin de paye fin mars (50%) et fin avril (50%).',
    approvedBy: 'Clarisse Bantsimba (RAF)',
  },
  {
    id: 'adv-002',
    employeeId: 'emp-003',
    employeeName: 'Alexandre Makosso',
    amount: 200000,
    currency: 'FCFA',
    requestDate: '2026-02-15',
    reason: 'Avance frais outillage d\'urgence pour meulage atelier',
    status: 'justifiee' as const,
    repaymentMode: 'especes' as const,
    justificationNotes: 'Justifié à 100% par facture de quincaillerie industrielle n° 8872 rattachée à la GED.',
    approvedBy: 'Dr. Joseph Ndoundo',
  },
];

export const INITIAL_LOSSES = [
  {
    id: 'loss-001',
    reference: 'PERTE-2026-01',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    amount: 650000,
    currency: 'FCFA',
    cause: 'rebut_matiere' as const,
    description: 'Chute de coupe non réutilisable et collerette bride endommagée lors du transport portuaire.',
    date: '2026-02-22',
    recordedBy: 'Ing. Paul Kimbembe',
  },
  {
    id: 'loss-002',
    reference: 'PERTE-2026-02',
    projectId: 'prj-002',
    projectName: 'Construction Charpente Métallique Silo 3 - Mfila',
    amount: 420000,
    currency: 'FCFA',
    cause: 'intemperies' as const,
    description: 'Arrêt de montage grue 48h suite à vents violents et fortes pluies.',
    date: '2026-03-08',
    recordedBy: 'Alexandre Makosso',
  },
];

export const INITIAL_CASH_MOVEMENTS = [
  {
    id: 'csh-001',
    account: 'banque_sgc' as const,
    direction: 'entree' as const,
    amount: 22500000,
    currency: 'FCFA',
    date: '2026-02-04',
    reference: 'VIR-CLI-TOT-01',
    label: 'Acompte 50% Projet Rénovation Lignes Tuyauterie HP Djeno',
    category: 'Vente / Encaissement Client',
    projectId: 'prj-001',
    balanceAfter: 48200000,
  },
  {
    id: 'csh-002',
    account: 'banque_sgc' as const,
    direction: 'sortie' as const,
    amount: 14500000,
    currency: 'FCFA',
    date: '2026-02-14',
    reference: 'VIR-FOUR-VAL-01',
    label: 'Règlement Fournisseur Tubes Vallourec Sch 80',
    category: 'Achat Matériel Tuyauterie',
    projectId: 'prj-001',
    balanceAfter: 33700000,
  },
  {
    id: 'csh-003',
    account: 'caisse_especes' as const,
    direction: 'sortie' as const,
    amount: 850000,
    currency: 'FCFA',
    date: '2026-03-12',
    reference: 'CAISSE-2026-44',
    label: 'Achat gasoil groupe électrogène chantier Djeno & petits consommables',
    category: 'Frais de Chantier Caisse',
    projectId: 'prj-001',
    balanceAfter: 2450000,
  },
  {
    id: 'csh-004',
    account: 'banque_ecobank' as const,
    direction: 'entree' as const,
    amount: 20000000,
    currency: 'FCFA',
    date: '2026-03-15',
    reference: 'VIR-CLI-DAN-02',
    label: 'Situation n°1 Travaux Silo Dangote Mfila',
    category: 'Vente / Encaissement Client',
    projectId: 'prj-002',
    balanceAfter: 28900000,
  },
];

export const INITIAL_PROJECT_PHOTOS = [
  {
    id: 'pht-001',
    projectId: 'prj-001',
    title: 'Alignement et pointage tuyauterie 6 pouces Sch 80',
    photoUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80',
    date: '2026-02-25',
    uploadedBy: 'Ing. Paul Kimbembe',
    phase: 'Soudage & Assemblage',
  },
  {
    id: 'pht-002',
    projectId: 'prj-001',
    title: 'Manifold épreuve hydraulique 65 bars sous contrôle Bureau Veritas',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    date: '2026-03-04',
    uploadedBy: 'Ing. Paul Kimbembe',
    phase: 'Hydrotest',
  },
  {
    id: 'pht-003',
    projectId: 'prj-002',
    title: 'Montage charpente métallique Silo 3 par grue mobile 50T',
    photoUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18615f8?auto=format&fit=crop&w=1200&q=80',
    date: '2026-03-10',
    uploadedBy: 'Alexandre Makosso',
    phase: 'Levage & Fixation',
  },
];

export const INITIAL_LEAVES = [
  {
    id: 'lev-001',
    employeeId: 'emp-005',
    employeeName: 'Moussa Traoré',
    type: 'mission_chantier' as const,
    startDate: '2026-02-10',
    endDate: '2026-04-15',
    status: 'en_cours' as const,
    destination: 'Base Industrielle Djeno, Pointe-Noire (Total)',
  },
  {
    id: 'lev-002',
    employeeId: 'emp-002',
    employeeName: 'Ing. Paul Kimbembe',
    type: 'mission_chantier' as const,
    startDate: '2026-01-20',
    endDate: '2026-05-30',
    status: 'en_cours' as const,
    destination: 'Supervision QA/QC Terminal Djeno',
  },
  {
    id: 'lev-003',
    employeeId: 'emp-003',
    employeeName: 'Alexandre Makosso',
    type: 'conge_annuel' as const,
    startDate: '2026-04-20',
    endDate: '2026-05-05',
    status: 'approuve' as const,
    destination: 'Brazzaville',
  },
];

export const INITIAL_STOCK_MOVEMENTS = [
  {
    id: 'stk-001',
    reference: 'BS-2026-012',
    type: 'sortie_chantier' as const,
    materialId: 'mat-001',
    materialName: 'Poste de soudage TIG/MMA Miller Dynasty 400',
    materialCode: 'MAT-SOU-01',
    quantity: 2,
    unit: 'unités',
    date: '2026-02-15',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    recipientName: 'Moussa Traoré (Soudeur HP)',
    emitterName: 'Alexandre Makosso (Magasinier Base)',
    isRestituable: true,
    returnStatus: 'en_cours' as const,
    notes: 'Outillage lourd sous caution et carnet de bord chantier.',
    documentId: 'doc-004',
  },
  {
    id: 'stk-002',
    reference: 'BS-2026-015',
    type: 'sortie_chantier' as const,
    materialId: 'mat-tub-01',
    materialName: 'Tubes acier carbone ASTM A106 Gr B 6" Sch 80',
    materialCode: 'FOUR-TUB-6',
    quantity: 120,
    unit: 'mètres',
    date: '2026-02-20',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    recipientName: 'Ing. Paul Kimbembe',
    emitterName: 'Alexandre Makosso (Magasinier Base)',
    isRestituable: false,
    returnStatus: 'non_applicable' as const,
    notes: 'Matériel coûteux consommable définitivement soudé sur lignes L-101 et L-102.',
    documentId: 'doc-001',
  },
  {
    id: 'stk-003',
    reference: 'BE-2026-004',
    type: 'entree_fournisseur' as const,
    materialId: 'mat-tub-01',
    materialName: 'Tubes acier carbone ASTM A106 Gr B 6" Sch 80',
    materialCode: 'FOUR-TUB-6',
    quantity: 450,
    unit: 'mètres',
    date: '2026-02-12',
    recipientName: 'Alexandre Makosso (Réceptionnaire Magasin)',
    emitterName: 'VALLOUREC TUBES AFRIQUE (Transporteur Portuaire)',
    isRestituable: false,
    returnStatus: 'non_applicable' as const,
    notes: 'Réception avec certificat matière 3.1 EN 10204 conforme.',
    documentId: 'doc-001',
  },
  {
    id: 'stk-004',
    reference: 'BS-2026-022',
    type: 'sortie_chantier' as const,
    materialId: 'mat-004',
    materialName: 'Pompe d\'Épreuve Hydraulique Haute Pression 250 Bars',
    materialCode: 'MAT-HYD-04',
    quantity: 1,
    unit: 'unité',
    date: '2026-03-02',
    projectId: 'prj-001',
    projectName: 'Rénovation Lignes Tuyauterie HP - Terminal Djeno',
    recipientName: 'Ing. Paul Kimbembe (Chef de Projet)',
    emitterName: 'Alexandre Makosso (Magasinier)',
    isRestituable: true,
    returnStatus: 'en_cours' as const,
    notes: 'Pour hydrotest 65 bars sous contrôle Bureau Veritas.',
    documentId: 'doc-002',
  },
];

export const INITIAL_CERTIFICATIONS = [
  {
    id: 'cert-001',
    employeeId: 'emp-005',
    employeeName: 'Moussa Traoré',
    title: 'Qualification Soudeur ASME IX 6G Tuyauterie HP (TIG/MMA)',
    category: 'soudage' as const,
    issuingBody: 'Bureau Veritas Afrique',
    issueDate: '2025-10-15',
    expiryDate: '2026-10-15',
    daysRemaining: 203,
    status: 'valide' as const,
    documentId: 'doc-002',
  },
  {
    id: 'cert-002',
    employeeId: 'emp-005',
    employeeName: 'Moussa Traoré',
    title: 'Visite Médicale Aptitude Offshore & Travail en Hauteur',
    category: 'medical_offshore' as const,
    issuingBody: 'Centre Médical Pétrolier Djeno',
    issueDate: '2025-04-10',
    expiryDate: '2026-04-10',
    daysRemaining: 17,
    status: 'expire_bientot' as const,
  },
  {
    id: 'cert-003',
    employeeId: 'emp-003',
    employeeName: 'Alexandre Makosso',
    title: 'Permis CACES R483 Grue Mobile & Élingage Industriel',
    category: 'caces_engins' as const,
    issuingBody: 'APAVE Congo',
    issueDate: '2021-04-05',
    expiryDate: '2026-04-05',
    daysRemaining: 12,
    status: 'expire_bientot' as const,
  },
  {
    id: 'cert-004',
    employeeId: 'emp-002',
    employeeName: 'Ing. Paul Kimbembe',
    title: 'Certification Contrôleur CND Niveau II (Ressuage & Radiographie)',
    category: 'cnd_ultrasons' as const,
    issuingBody: 'COFREND / Bureau Veritas',
    issueDate: '2024-12-15',
    expiryDate: '2027-12-15',
    daysRemaining: 447,
    status: 'valide' as const,
  },
  {
    id: 'cert-005',
    employeeId: 'emp-005',
    employeeName: 'Moussa Traoré',
    title: 'Habilitation Sécurité SST & ATEX Zone 1',
    category: 'securite_sst' as const,
    issuingBody: 'TotalEnergies E&P Safety Center',
    issueDate: '2025-11-20',
    expiryDate: '2026-11-20',
    daysRemaining: 240,
    status: 'valide' as const,
  },
];

